repos:
    - repo: https://github.com/PyCQA/isort
      rev: 5.12.0
      hooks:
          - id: isort
            name: isort (python)
    - repo: https://github.com/psf/black
      rev: 23.3.0
      hooks:
          - id: black
            args: [--line-length=119, --target-version=py39]
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.0.0-alpha.9-for-vscode
      hooks:
          - id: prettier
